// This file is @generated by prost-build.
/// TODO(jcohen): This should almost certainly be moved to `urc-server-epic`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ComplianceCheck {
    #[prost(string, tag = "1")]
    pub revision: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub revision_number: u64,
    #[prost(string, tag = "3")]
    pub branch: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub repository: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub ip_addr: ::prost::alloc::string::String,
}
impl ::prost::Name for ComplianceCheck {
    const NAME: &'static str = "ComplianceCheck";
    const PACKAGE: &'static str = "epic.events";
    fn full_name() -> ::prost::alloc::string::String {
        "epic.events.ComplianceCheck".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/epic.events.ComplianceCheck".into()
    }
}
