// This file is @generated by prost-build.
/// An event published when a branch is created on the server
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchCreated {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchCreated {
    const NAME: &'static str = "BranchCreated";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.BranchCreated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.BranchCreated".into()
    }
}
/// Represents a revision pushed event
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchPushed {
    #[prost(bytes = "bytes", tag = "1")]
    pub revision: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "2")]
    pub revision_number: u64,
    #[prost(bytes = "bytes", tag = "3")]
    pub branch: ::prost::bytes::Bytes,
    #[prost(string, tag = "4")]
    pub user_id: ::prost::alloc::string::String,
}
impl ::prost::Name for BranchPushed {
    const NAME: &'static str = "BranchPushed";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.BranchPushed".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.BranchPushed".into()
    }
}
/// An event published when a branch is deleted from the server
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchDeleted {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchDeleted {
    const NAME: &'static str = "BranchDeleted";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.BranchDeleted".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.BranchDeleted".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceLocked {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub resources: ::prost::alloc::vec::Vec<super::super::urc::lock::Resource>,
}
impl ::prost::Name for ResourceLocked {
    const NAME: &'static str = "ResourceLocked";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.ResourceLocked".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.ResourceLocked".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceUnlocked {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub resources: ::prost::alloc::vec::Vec<super::super::urc::lock::Resource>,
}
impl ::prost::Name for ResourceUnlocked {
    const NAME: &'static str = "ResourceUnlocked";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.ResourceUnlocked".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.ResourceUnlocked".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Obliterate {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<super::super::urc::model::Address>,
    #[prost(bytes = "bytes", tag = "2")]
    pub repository: ::prost::bytes::Bytes,
}
impl ::prost::Name for Obliterate {
    const NAME: &'static str = "Obliterate";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.Obliterate".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.Obliterate".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExtensionEvent {
    /// Globally unique event identifier, e.g. `org.lore.security.compliance`
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub payload: ::core::option::Option<::prost_types::Any>,
}
impl ::prost::Name for ExtensionEvent {
    const NAME: &'static str = "ExtensionEvent";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.ExtensionEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.ExtensionEvent".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// UUID of the event
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Timestamp object that supports seconds and nanoseconds
    #[prost(message, optional, tag = "2")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    /// The repository to which the event applies
    #[prost(bytes = "bytes", tag = "3")]
    pub repository: ::prost::bytes::Bytes,
    /// Event payload
    #[prost(oneof = "event::Event", tags = "4, 5, 6, 7, 8, 9, 10")]
    pub event: ::core::option::Option<event::Event>,
}
/// Nested message and enum types in `Event`.
pub mod event {
    /// Event payload
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "4")]
        Other(super::ExtensionEvent),
        #[prost(message, tag = "5")]
        BranchPushed(super::BranchPushed),
        #[prost(message, tag = "6")]
        ResourceLocked(super::ResourceLocked),
        #[prost(message, tag = "7")]
        ResourceUnlocked(super::ResourceUnlocked),
        #[prost(message, tag = "8")]
        BranchDeleted(super::BranchDeleted),
        #[prost(message, tag = "9")]
        BranchCreated(super::BranchCreated),
        /// TODO(jcohen): We may eventually want to investigate supporting propagation of obliterate events between instances
        /// directly using the storage layer, rather than relying on an external notification system for coordination.
        #[prost(message, tag = "10")]
        Obliterate(super::Obliterate),
    }
}
impl ::prost::Name for Event {
    const NAME: &'static str = "Event";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.Event".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.Event".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub repository: ::prost::bytes::Bytes,
}
impl ::prost::Name for SubscribeRequest {
    const NAME: &'static str = "SubscribeRequest";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.SubscribeRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.SubscribeRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishRequest {
    #[prost(message, optional, tag = "1")]
    pub event: ::core::option::Option<Event>,
}
impl ::prost::Name for PublishRequest {
    const NAME: &'static str = "PublishRequest";
    const PACKAGE: &'static str = "lore.notification";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.notification.PublishRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.notification.PublishRequest".into()
    }
}
/// Generated client implementations.
pub mod notification_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct NotificationServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl NotificationServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> NotificationServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> NotificationServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            NotificationServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn subscribe(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Event>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.notification.NotificationService/Subscribe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.notification.NotificationService", "Subscribe"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn publish(
            &mut self,
            request: impl tonic::IntoRequest<super::PublishRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.notification.NotificationService/Publish",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.notification.NotificationService", "Publish"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod notification_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with NotificationServiceServer.
    #[async_trait]
    pub trait NotificationService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Subscribe method.
        type SubscribeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Event, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn subscribe(
            &self,
            request: tonic::Request<super::SubscribeRequest>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeStream>, tonic::Status>;
        async fn publish(
            &self,
            request: tonic::Request<super::PublishRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct NotificationServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> NotificationServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for NotificationServiceServer<T>
    where
        T: NotificationService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.notification.NotificationService/Subscribe" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeSvc<T: NotificationService>(pub Arc<T>);
                    impl<
                        T: NotificationService,
                    > tonic::server::ServerStreamingService<super::SubscribeRequest>
                    for SubscribeSvc<T> {
                        type Response = super::Event;
                        type ResponseStream = T::SubscribeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubscribeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NotificationService>::subscribe(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.notification.NotificationService/Publish" => {
                    #[allow(non_camel_case_types)]
                    struct PublishSvc<T: NotificationService>(pub Arc<T>);
                    impl<
                        T: NotificationService,
                    > tonic::server::UnaryService<super::PublishRequest>
                    for PublishSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PublishRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NotificationService>::publish(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PublishSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for NotificationServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.notification.NotificationService";
    impl<T> tonic::server::NamedService for NotificationServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
