// This file is @generated by prost-build.
/// In the case of a partial put, only the address and metadata (flags and sizes)
/// are required.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Fragment {
    #[prost(uint32, tag = "1")]
    pub flags: u32,
    #[prost(uint32, tag = "2")]
    pub size_payload: u32,
    #[prost(uint64, tag = "3")]
    pub size_content: u64,
}
impl ::prost::Name for Fragment {
    const NAME: &'static str = "Fragment";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Fragment".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Fragment".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(bytes = "bytes", tag = "1")]
    pub hash: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub context: ::prost::bytes::Bytes,
}
impl ::prost::Name for Address {
    const NAME: &'static str = "Address";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Address".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Address".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Repository {
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "3")]
    pub metadata: ::prost::bytes::Bytes,
}
impl ::prost::Name for Repository {
    const NAME: &'static str = "Repository";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Repository".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Repository".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchPoint {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub revision: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchPoint {
    const NAME: &'static str = "BranchPoint";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchPoint".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchPoint".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Branch {
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Deprecated, use stack field instead
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub parent_deprecated: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", tag = "4")]
    pub latest: ::prost::bytes::Bytes,
    /// Deprecated, use stack field instead
    #[prost(bytes = "bytes", optional, tag = "5")]
    pub branch_point_deprecated: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, tag = "6")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub created: u64,
    #[prost(string, tag = "8")]
    pub category: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "9")]
    pub stack: ::prost::alloc::vec::Vec<BranchPoint>,
}
impl ::prost::Name for Branch {
    const NAME: &'static str = "Branch";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Branch".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Branch".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(enumeration = "MetadataType", tag = "3")]
    pub metadata_type: i32,
}
impl ::prost::Name for Metadata {
    const NAME: &'static str = "Metadata";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Metadata".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Metadata".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Revision {
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    #[prost(string, tag = "2")]
    pub commit_message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
    #[prost(string, tag = "4")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub committed_by: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub metadata: ::prost::alloc::vec::Vec<Metadata>,
    #[prost(bytes = "bytes", optional, tag = "11")]
    pub parent_self: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "12")]
    pub parent_other: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint64, tag = "13")]
    pub number: u64,
    #[prost(uint64, optional, tag = "14")]
    pub parent_self_number: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "15")]
    pub parent_other_number: ::core::option::Option<u64>,
}
impl ::prost::Name for Revision {
    const NAME: &'static str = "Revision";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Revision".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Revision".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionItem {
    #[prost(uint64, tag = "1")]
    pub number: u64,
    #[prost(bytes = "bytes", tag = "2")]
    pub signature: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub metadata: ::prost::bytes::Bytes,
}
impl ::prost::Name for RevisionItem {
    const NAME: &'static str = "RevisionItem";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionItem".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Path {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "2")]
    pub address: ::prost::bytes::Bytes,
    #[prost(enumeration = "PathType", tag = "3")]
    pub r#type: i32,
}
impl ::prost::Name for Path {
    const NAME: &'static str = "Path";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Path".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Path".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PathDiff {
    #[prost(message, optional, tag = "1")]
    pub from: ::core::option::Option<Path>,
    #[prost(message, optional, tag = "2")]
    pub to: ::core::option::Option<Path>,
    #[prost(bool, tag = "3")]
    pub automerged: bool,
}
impl ::prost::Name for PathDiff {
    const NAME: &'static str = "PathDiff";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.PathDiff".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.PathDiff".into()
    }
}
/// //////////////////////////////////////////
/// API objects
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchCreateRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
    /// Deprecated, use stack field instead
    #[prost(bytes = "bytes", optional, tag = "2")]
    pub revision_deprecated: ::core::option::Option<::prost::bytes::Bytes>,
    /// Deprecated, use stack field instead
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub parent_deprecated: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub created: u64,
    #[prost(string, tag = "7")]
    pub category: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "8")]
    pub stack: ::prost::alloc::vec::Vec<BranchPoint>,
}
impl ::prost::Name for BranchCreateRequest {
    const NAME: &'static str = "BranchCreateRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchCreateRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchCreateRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchCreateResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub revision: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchCreateResponse {
    const NAME: &'static str = "BranchCreateResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchCreateResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchCreateResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchDeleteRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchDeleteRequest {
    const NAME: &'static str = "BranchDeleteRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchDeleteRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchDeleteRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchDeleteResponse {}
impl ::prost::Name for BranchDeleteResponse {
    const NAME: &'static str = "BranchDeleteResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchDeleteResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchDeleteResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchProtectRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchProtectRequest {
    const NAME: &'static str = "BranchProtectRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchProtectRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchProtectRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchProtectResponse {}
impl ::prost::Name for BranchProtectResponse {
    const NAME: &'static str = "BranchProtectResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchProtectResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchProtectResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchUnprotectRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchUnprotectRequest {
    const NAME: &'static str = "BranchUnprotectRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchUnprotectRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchUnprotectRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchUnprotectResponse {}
impl ::prost::Name for BranchUnprotectResponse {
    const NAME: &'static str = "BranchUnprotectResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchUnprotectResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchUnprotectResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchQueryRequest {
    #[prost(oneof = "branch_query_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<branch_query_request::Query>,
}
/// Nested message and enum types in `BranchQueryRequest`.
pub mod branch_query_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        #[prost(bytes, tag = "1")]
        Id(::prost::bytes::Bytes),
        #[prost(string, tag = "2")]
        Name(::prost::alloc::string::String),
    }
}
impl ::prost::Name for BranchQueryRequest {
    const NAME: &'static str = "BranchQueryRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchQueryRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchQueryRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchQueryResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub revision: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub metadata: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub id: ::prost::bytes::Bytes,
    #[prost(bool, tag = "4")]
    pub deleted: bool,
}
impl ::prost::Name for BranchQueryResponse {
    const NAME: &'static str = "BranchQueryResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchQueryResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchQueryResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchGetRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchGetRequest {
    const NAME: &'static str = "BranchGetRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchGetRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchGetResponse {
    #[prost(message, optional, tag = "1")]
    pub branch: ::core::option::Option<Branch>,
}
impl ::prost::Name for BranchGetResponse {
    const NAME: &'static str = "BranchGetResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchGetResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchListRequest {}
impl ::prost::Name for BranchListRequest {
    const NAME: &'static str = "BranchListRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchListRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchListResponse {
    #[prost(message, repeated, tag = "1")]
    pub branches: ::prost::alloc::vec::Vec<Branch>,
}
impl ::prost::Name for BranchListResponse {
    const NAME: &'static str = "BranchListResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchListResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchPushRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub revision: ::prost::bytes::Bytes,
    #[prost(bool, tag = "3")]
    pub force: bool,
    #[prost(bool, tag = "4")]
    pub fast_forward_merge: bool,
}
impl ::prost::Name for BranchPushRequest {
    const NAME: &'static str = "BranchPushRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchPushRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchPushRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchPushResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(bool, tag = "2")]
    pub fast_forward_merged: bool,
    #[prost(bytes = "bytes", tag = "3")]
    pub revision: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "4")]
    pub revision_number: u64,
    #[prost(string, optional, tag = "5")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for BranchPushResponse {
    const NAME: &'static str = "BranchPushResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchPushResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchPushResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchDiffRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch_target: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub branch_source: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub revision_target: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "4")]
    pub revision_source: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bool, tag = "5")]
    pub autoresolve: bool,
}
impl ::prost::Name for BranchDiffRequest {
    const NAME: &'static str = "BranchDiffRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchDiffRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchDiffRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Conflict {
    #[prost(message, optional, tag = "1")]
    pub diff_base: ::core::option::Option<PathDiff>,
    #[prost(message, optional, tag = "2")]
    pub diff_compare: ::core::option::Option<PathDiff>,
}
impl ::prost::Name for Conflict {
    const NAME: &'static str = "Conflict";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Conflict".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Conflict".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchDiffResponse {
    #[prost(message, repeated, tag = "1")]
    pub diffs: ::prost::alloc::vec::Vec<PathDiff>,
    #[prost(message, repeated, tag = "2")]
    pub conflicts: ::prost::alloc::vec::Vec<Conflict>,
    #[prost(message, optional, tag = "3")]
    pub branch_target: ::core::option::Option<Branch>,
    #[prost(message, optional, tag = "4")]
    pub branch_source: ::core::option::Option<Branch>,
    #[prost(bytes = "bytes", tag = "5")]
    pub revision_target: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "6")]
    pub revision_source: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "7")]
    pub revision_base: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchDiffResponse {
    const NAME: &'static str = "BranchDiffResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchDiffResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchDiffResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchRevisionListRequest {
    #[prost(bytes = "bytes", optional, tag = "1")]
    pub branch: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag = "2")]
    pub limit: ::core::option::Option<u32>,
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub source: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "4")]
    pub target: ::core::option::Option<::prost::bytes::Bytes>,
}
impl ::prost::Name for BranchRevisionListRequest {
    const NAME: &'static str = "BranchRevisionListRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchRevisionListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchRevisionListRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchRevisionListResponse {
    #[prost(message, repeated, tag = "1")]
    pub revisions: ::prost::alloc::vec::Vec<Revision>,
    #[prost(bool, tag = "2")]
    pub has_more: bool,
}
impl ::prost::Name for BranchRevisionListResponse {
    const NAME: &'static str = "BranchRevisionListResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchRevisionListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchRevisionListResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionIdentifer {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "2")]
    pub number: u64,
}
impl ::prost::Name for RevisionIdentifer {
    const NAME: &'static str = "RevisionIdentifer";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionIdentifer".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionIdentifer".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionListRequest {
    #[prost(oneof = "revision_list_request::Start", tags = "1, 2")]
    pub start: ::core::option::Option<revision_list_request::Start>,
}
/// Nested message and enum types in `RevisionListRequest`.
pub mod revision_list_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Start {
        #[prost(message, tag = "1")]
        Identifier(super::RevisionIdentifer),
        #[prost(bytes, tag = "2")]
        Signature(::prost::bytes::Bytes),
    }
}
impl ::prost::Name for RevisionListRequest {
    const NAME: &'static str = "RevisionListRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionListRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevisionListResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub next_revision: ::prost::bytes::Bytes,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<RevisionItem>,
    #[prost(bytes = "bytes", tag = "3")]
    pub previous_revision: ::prost::bytes::Bytes,
}
impl ::prost::Name for RevisionListResponse {
    const NAME: &'static str = "RevisionListResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionListResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetResponse {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "2")]
    pub fragment: ::core::option::Option<Fragment>,
    #[prost(bytes = "bytes", tag = "3")]
    pub payload: ::prost::bytes::Bytes,
}
impl ::prost::Name for GetResponse {
    const NAME: &'static str = "GetResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.GetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.GetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutRequest {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "2")]
    pub fragment: ::core::option::Option<Fragment>,
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub payload: ::core::option::Option<::prost::bytes::Bytes>,
}
impl ::prost::Name for PutRequest {
    const NAME: &'static str = "PutRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.PutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.PutRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplicationPutRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub repository_id: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "2")]
    pub put_request: ::core::option::Option<PutRequest>,
}
impl ::prost::Name for ReplicationPutRequest {
    const NAME: &'static str = "ReplicationPutRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.ReplicationPutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.ReplicationPutRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutResponse {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
}
impl ::prost::Name for PutResponse {
    const NAME: &'static str = "PutResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.PutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.PutResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRequest {
    #[prost(message, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<Address>,
}
impl ::prost::Name for QueryRequest {
    const NAME: &'static str = "QueryRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.QueryRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.QueryRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryResponse {
    #[prost(enumeration = "FragmentState", repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<i32>,
}
impl ::prost::Name for QueryResponse {
    const NAME: &'static str = "QueryResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.QueryResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.QueryResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingRequest {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
}
impl ::prost::Name for PingRequest {
    const NAME: &'static str = "PingRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.PingRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.PingRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingResponse {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
}
impl ::prost::Name for PingResponse {
    const NAME: &'static str = "PingResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.PingResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.PingResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryCreateRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "4")]
    pub default_branch_id: ::prost::bytes::Bytes,
    #[prost(string, tag = "5")]
    pub default_branch_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub creator: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub created: u64,
}
impl ::prost::Name for RepositoryCreateRequest {
    const NAME: &'static str = "RepositoryCreateRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryCreateRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryCreateRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryCreateResponse {
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<Repository>,
}
impl ::prost::Name for RepositoryCreateResponse {
    const NAME: &'static str = "RepositoryCreateResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryCreateResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryCreateResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryDeleteRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryDeleteRequest {
    const NAME: &'static str = "RepositoryDeleteRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryDeleteRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryDeleteRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryDeleteResponse {}
impl ::prost::Name for RepositoryDeleteResponse {
    const NAME: &'static str = "RepositoryDeleteResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryDeleteResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryDeleteResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryQueryRequest {
    #[prost(oneof = "repository_query_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<repository_query_request::Query>,
}
/// Nested message and enum types in `RepositoryQueryRequest`.
pub mod repository_query_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        #[prost(bytes, tag = "1")]
        Id(::prost::bytes::Bytes),
        #[prost(string, tag = "2")]
        Name(::prost::alloc::string::String),
    }
}
impl ::prost::Name for RepositoryQueryRequest {
    const NAME: &'static str = "RepositoryQueryRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryQueryRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryQueryRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryQueryResponse {
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<Repository>,
}
impl ::prost::Name for RepositoryQueryResponse {
    const NAME: &'static str = "RepositoryQueryResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryQueryResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryQueryResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryListRequest {}
impl ::prost::Name for RepositoryListRequest {
    const NAME: &'static str = "RepositoryListRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryListRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryListResponse {
    #[prost(message, repeated, tag = "1")]
    pub repositories: ::prost::alloc::vec::Vec<Repository>,
}
impl ::prost::Name for RepositoryListResponse {
    const NAME: &'static str = "RepositoryListResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryListResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataGetRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub repository_id: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataGetRequest {
    const NAME: &'static str = "RepositoryMetadataGetRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryMetadataGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryMetadataGetRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataGetResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub metadata_hash: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataGetResponse {
    const NAME: &'static str = "RepositoryMetadataGetResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryMetadataGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryMetadataGetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataSetRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub repository_id: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub expected_hash: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub new_hash: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataSetRequest {
    const NAME: &'static str = "RepositoryMetadataSetRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryMetadataSetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryMetadataSetRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataSetResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(bytes = "bytes", tag = "2")]
    pub current_hash: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataSetResponse {
    const NAME: &'static str = "RepositoryMetadataSetResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RepositoryMetadataSetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RepositoryMetadataSetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataGetRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch_id: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataGetRequest {
    const NAME: &'static str = "BranchMetadataGetRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchMetadataGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchMetadataGetRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataGetResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub metadata_hash: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataGetResponse {
    const NAME: &'static str = "BranchMetadataGetResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchMetadataGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchMetadataGetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataSetRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub branch_id: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub expected_hash: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub new_hash: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataSetRequest {
    const NAME: &'static str = "BranchMetadataSetRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchMetadataSetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchMetadataSetRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataSetResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(bytes = "bytes", tag = "2")]
    pub current_hash: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataSetResponse {
    const NAME: &'static str = "BranchMetadataSetResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.BranchMetadataSetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.BranchMetadataSetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionDescribeRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
}
impl ::prost::Name for RevisionDescribeRequest {
    const NAME: &'static str = "RevisionDescribeRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionDescribeRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionDescribeRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevisionDescribeResponse {
    #[prost(message, optional, tag = "1")]
    pub revision: ::core::option::Option<Revision>,
}
impl ::prost::Name for RevisionDescribeResponse {
    const NAME: &'static str = "RevisionDescribeResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionDescribeResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionDescribeResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionDiffRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub revision_from: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub revision_to: ::prost::bytes::Bytes,
}
impl ::prost::Name for RevisionDiffRequest {
    const NAME: &'static str = "RevisionDiffRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionDiffRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionDiffRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevisionDiffResponse {
    #[prost(message, repeated, tag = "1")]
    pub diffs: ::prost::alloc::vec::Vec<PathDiff>,
}
impl ::prost::Name for RevisionDiffResponse {
    const NAME: &'static str = "RevisionDiffResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionDiffResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionDiffResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionStateHistoryRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub revision: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "2")]
    pub depth: u32,
    #[prost(bool, tag = "3")]
    pub with_metadata: bool,
    #[prost(bool, tag = "4")]
    pub follow_merge: bool,
}
impl ::prost::Name for RevisionStateHistoryRequest {
    const NAME: &'static str = "RevisionStateHistoryRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionStateHistoryRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionStateHistoryRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionStateHistoryResponse {
    #[prost(bytes = "bytes", repeated, tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", repeated, tag = "2")]
    pub metadata: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
}
impl ::prost::Name for RevisionStateHistoryResponse {
    const NAME: &'static str = "RevisionStateHistoryResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionStateHistoryResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionStateHistoryResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionTreeRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub revision: ::prost::bytes::Bytes,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub max_depth: u32,
}
impl ::prost::Name for RevisionTreeRequest {
    const NAME: &'static str = "RevisionTreeRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionTreeRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionTreeRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevisionTreeResponse {
    #[prost(message, repeated, tag = "1")]
    pub paths: ::prost::alloc::vec::Vec<Path>,
}
impl ::prost::Name for RevisionTreeResponse {
    const NAME: &'static str = "RevisionTreeResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.RevisionTreeResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.RevisionTreeResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObliterateRequest {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
}
impl ::prost::Name for ObliterateRequest {
    const NAME: &'static str = "ObliterateRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.ObliterateRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.ObliterateRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObliterateResponse {}
impl ::prost::Name for ObliterateResponse {
    const NAME: &'static str = "ObliterateResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.ObliterateResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.ObliterateResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvironmentEndpoint {
    #[prost(string, tag = "1")]
    pub auth_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub repository_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub storage_url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub revision_url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub lock_url: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub notification_url: ::prost::alloc::string::String,
}
impl ::prost::Name for EnvironmentEndpoint {
    const NAME: &'static str = "EnvironmentEndpoint";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.EnvironmentEndpoint".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.EnvironmentEndpoint".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvironmentConfig {
    #[prost(uint32, tag = "1")]
    pub max_query_batch: u32,
    #[prost(enumeration = "CompressionMode", optional, tag = "2")]
    pub compression_mode: ::core::option::Option<i32>,
}
impl ::prost::Name for EnvironmentConfig {
    const NAME: &'static str = "EnvironmentConfig";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.EnvironmentConfig".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.EnvironmentConfig".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Environment {
    #[prost(message, optional, tag = "1")]
    pub endpoint: ::core::option::Option<EnvironmentEndpoint>,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<EnvironmentConfig>,
}
impl ::prost::Name for Environment {
    const NAME: &'static str = "Environment";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.Environment".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.Environment".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvironmentGetRequest {}
impl ::prost::Name for EnvironmentGetRequest {
    const NAME: &'static str = "EnvironmentGetRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.EnvironmentGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.EnvironmentGetRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvironmentGetResponse {
    #[prost(message, optional, tag = "1")]
    pub environment: ::core::option::Option<Environment>,
}
impl ::prost::Name for EnvironmentGetResponse {
    const NAME: &'static str = "EnvironmentGetResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.EnvironmentGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.EnvironmentGetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRequest {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
    #[prost(bool, tag = "2")]
    pub heal: bool,
}
impl ::prost::Name for VerifyRequest {
    const NAME: &'static str = "VerifyRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.VerifyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.VerifyRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyResponse {
    #[prost(enumeration = "HealResult", tag = "1")]
    pub healed: i32,
    #[prost(bool, tag = "2")]
    pub corrupted: bool,
}
impl ::prost::Name for VerifyResponse {
    const NAME: &'static str = "VerifyResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.VerifyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.VerifyResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CopyRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub source_repository_id: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "2")]
    pub source_address: ::core::option::Option<Address>,
    /// Destination context. The destination address is
    /// (target_repository, source_address.hash, target_context). When omitted (zero bytes), the
    /// server treats the destination context as the source's, preserving the legacy semantics.
    #[prost(bytes = "bytes", tag = "3")]
    pub target_context: ::prost::bytes::Bytes,
}
impl ::prost::Name for CopyRequest {
    const NAME: &'static str = "CopyRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.CopyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.CopyRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CopyResponse {
    #[prost(message, optional, tag = "1")]
    pub source_address: ::core::option::Option<Address>,
}
impl ::prost::Name for CopyResponse {
    const NAME: &'static str = "CopyResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.CopyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.CopyResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableLoadRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub key: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "2")]
    pub key_type: u32,
}
impl ::prost::Name for MutableLoadRequest {
    const NAME: &'static str = "MutableLoadRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.MutableLoadRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.MutableLoadRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableLoadResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub value: ::prost::bytes::Bytes,
}
impl ::prost::Name for MutableLoadResponse {
    const NAME: &'static str = "MutableLoadResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.MutableLoadResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.MutableLoadResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableStoreRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub key: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub value: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "3")]
    pub key_type: u32,
}
impl ::prost::Name for MutableStoreRequest {
    const NAME: &'static str = "MutableStoreRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.MutableStoreRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.MutableStoreRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableStoreResponse {}
impl ::prost::Name for MutableStoreResponse {
    const NAME: &'static str = "MutableStoreResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.MutableStoreResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.MutableStoreResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableCompareAndSwapRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub key: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub expected: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub value: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "4")]
    pub key_type: u32,
}
impl ::prost::Name for MutableCompareAndSwapRequest {
    const NAME: &'static str = "MutableCompareAndSwapRequest";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.MutableCompareAndSwapRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.MutableCompareAndSwapRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableCompareAndSwapResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub current_value: ::prost::bytes::Bytes,
}
impl ::prost::Name for MutableCompareAndSwapResponse {
    const NAME: &'static str = "MutableCompareAndSwapResponse";
    const PACKAGE: &'static str = "urc.model";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.model.MutableCompareAndSwapResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.model.MutableCompareAndSwapResponse".into()
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FragmentState {
    FoundInContext = 0,
    Found = 1,
    NotFound = 2,
    Unknown = 3,
}
impl FragmentState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FoundInContext => "FOUND_IN_CONTEXT",
            Self::Found => "FOUND",
            Self::NotFound => "NOT_FOUND",
            Self::Unknown => "UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FOUND_IN_CONTEXT" => Some(Self::FoundInContext),
            "FOUND" => Some(Self::Found),
            "NOT_FOUND" => Some(Self::NotFound),
            "UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MetadataType {
    Address = 0,
    Boolean = 1,
    Binary = 2,
    Context = 3,
    Hash = 4,
    Numeric = 5,
    String = 6,
}
impl MetadataType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Address => "ADDRESS",
            Self::Boolean => "BOOLEAN",
            Self::Binary => "BINARY",
            Self::Context => "CONTEXT",
            Self::Hash => "HASH",
            Self::Numeric => "NUMERIC",
            Self::String => "STRING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ADDRESS" => Some(Self::Address),
            "BOOLEAN" => Some(Self::Boolean),
            "BINARY" => Some(Self::Binary),
            "CONTEXT" => Some(Self::Context),
            "HASH" => Some(Self::Hash),
            "NUMERIC" => Some(Self::Numeric),
            "STRING" => Some(Self::String),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PathType {
    Directory = 0,
    File = 1,
    Link = 2,
}
impl PathType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Directory => "DIRECTORY",
            Self::File => "FILE",
            Self::Link => "LINK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIRECTORY" => Some(Self::Directory),
            "FILE" => Some(Self::File),
            "LINK" => Some(Self::Link),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompressionMode {
    NotSpecified = 0,
    NoCompression = 1,
    Lz4 = 2,
    Oodle = 3,
    Zstd = 4,
}
impl CompressionMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotSpecified => "NotSpecified",
            Self::NoCompression => "NoCompression",
            Self::Lz4 => "Lz4",
            Self::Oodle => "Oodle",
            Self::Zstd => "Zstd",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NotSpecified" => Some(Self::NotSpecified),
            "NoCompression" => Some(Self::NoCompression),
            "Lz4" => Some(Self::Lz4),
            "Oodle" => Some(Self::Oodle),
            "Zstd" => Some(Self::Zstd),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HealResult {
    NotAttempted = 0,
    Success = 1,
    Failed = 2,
}
impl HealResult {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotAttempted => "NOT_ATTEMPTED",
            Self::Success => "SUCCESS",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOT_ATTEMPTED" => Some(Self::NotAttempted),
            "SUCCESS" => Some(Self::Success),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
