// This file is @generated by prost-build.
/// Represents the resource being locked in the repository
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Resource {
    /// Branch ID
    #[prost(bytes = "bytes", tag = "1")]
    pub branch: ::prost::bytes::Bytes,
    /// Hash for the resource
    #[prost(bytes = "bytes", tag = "2")]
    pub hash: ::prost::bytes::Bytes,
    /// Human readable description of the resource (i.e. file path, property name,
    /// etc)
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
}
impl ::prost::Name for Resource {
    const NAME: &'static str = "Resource";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.Resource".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.Resource".into()
    }
}
/// Represents the lock on a resource
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Lock {
    /// Resource reference
    #[prost(message, optional, tag = "1")]
    pub resource: ::core::option::Option<Resource>,
    /// The server will store the user's ID provided with the
    /// request's auth info
    #[prost(string, tag = "2")]
    pub owner: ::prost::alloc::string::String,
    /// Lock timestamp
    #[prost(message, optional, tag = "3")]
    pub locked_at: ::core::option::Option<::prost_types::Timestamp>,
}
impl ::prost::Name for Lock {
    const NAME: &'static str = "Lock";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.Lock".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.Lock".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockRequest {
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<Resource>,
}
impl ::prost::Name for LockRequest {
    const NAME: &'static str = "LockRequest";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.LockRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.LockRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockResponse {
    /// List of created locks
    #[prost(message, repeated, tag = "1")]
    pub locks: ::prost::alloc::vec::Vec<Lock>,
}
impl ::prost::Name for LockResponse {
    const NAME: &'static str = "LockResponse";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.LockResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.LockResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryRequest {
    #[prost(bytes = "bytes", optional, tag = "1")]
    pub branch: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag = "2")]
    pub owner: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for QueryRequest {
    const NAME: &'static str = "QueryRequest";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.QueryRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.QueryRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryResponse {
    #[prost(message, repeated, tag = "1")]
    pub result: ::prost::alloc::vec::Vec<Lock>,
}
impl ::prost::Name for QueryResponse {
    const NAME: &'static str = "QueryResponse";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.QueryResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.QueryResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusRequest {
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<Resource>,
}
impl ::prost::Name for StatusRequest {
    const NAME: &'static str = "StatusRequest";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.StatusRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.StatusRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    /// List of locks found
    /// NOTE: We might want to consider just boolean returns in order?
    #[prost(message, repeated, tag = "1")]
    pub locks: ::prost::alloc::vec::Vec<Lock>,
}
impl ::prost::Name for StatusResponse {
    const NAME: &'static str = "StatusResponse";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.StatusResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.StatusResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockRequest {
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<Resource>,
}
impl ::prost::Name for UnlockRequest {
    const NAME: &'static str = "UnlockRequest";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.UnlockRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.UnlockRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockResponse {
    /// List of resources unlocked
    /// NOTE: Same as above, maybe booleans in order?
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<Resource>,
}
impl ::prost::Name for UnlockResponse {
    const NAME: &'static str = "UnlockResponse";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.UnlockResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.UnlockResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdminLockRequest {
    #[prost(message, repeated, tag = "1")]
    pub resources: ::prost::alloc::vec::Vec<Resource>,
    #[prost(string, tag = "2")]
    pub owner: ::prost::alloc::string::String,
}
impl ::prost::Name for AdminLockRequest {
    const NAME: &'static str = "AdminLockRequest";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.AdminLockRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.AdminLockRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdminLockResponse {
    /// List of created locks
    #[prost(message, repeated, tag = "1")]
    pub locks: ::prost::alloc::vec::Vec<Lock>,
}
impl ::prost::Name for AdminLockResponse {
    const NAME: &'static str = "AdminLockResponse";
    const PACKAGE: &'static str = "urc.lock";
    fn full_name() -> ::prost::alloc::string::String {
        "urc.lock.AdminLockResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/urc.lock.AdminLockResponse".into()
    }
}
/// Generated client implementations.
pub mod lock_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct LockServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl LockServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> LockServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> LockServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            LockServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Locks resources, errors if already locked
        pub async fn lock(
            &mut self,
            request: impl tonic::IntoRequest<super::LockRequest>,
        ) -> std::result::Result<tonic::Response<super::LockResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/urc.lock.LockService/Lock",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("urc.lock.LockService", "Lock"));
            self.inner.unary(req, path, codec).await
        }
        /// Query for locks
        pub async fn query(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/urc.lock.LockService/Query",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("urc.lock.LockService", "Query"));
            self.inner.unary(req, path, codec).await
        }
        /// Get lock status
        pub async fn status(
            &mut self,
            request: impl tonic::IntoRequest<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/urc.lock.LockService/Status",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("urc.lock.LockService", "Status"));
            self.inner.unary(req, path, codec).await
        }
        /// Unlocks resources, no-ops if no lock exists
        pub async fn unlock(
            &mut self,
            request: impl tonic::IntoRequest<super::UnlockRequest>,
        ) -> std::result::Result<tonic::Response<super::UnlockResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/urc.lock.LockService/Unlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("urc.lock.LockService", "Unlock"));
            self.inner.unary(req, path, codec).await
        }
        /// Locks resources for another user
        pub async fn admin_lock(
            &mut self,
            request: impl tonic::IntoRequest<super::AdminLockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AdminLockResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/urc.lock.LockService/AdminLock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("urc.lock.LockService", "AdminLock"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod lock_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with LockServiceServer.
    #[async_trait]
    pub trait LockService: std::marker::Send + std::marker::Sync + 'static {
        /// Locks resources, errors if already locked
        async fn lock(
            &self,
            request: tonic::Request<super::LockRequest>,
        ) -> std::result::Result<tonic::Response<super::LockResponse>, tonic::Status>;
        /// Query for locks
        async fn query(
            &self,
            request: tonic::Request<super::QueryRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryResponse>, tonic::Status>;
        /// Get lock status
        async fn status(
            &self,
            request: tonic::Request<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status>;
        /// Unlocks resources, no-ops if no lock exists
        async fn unlock(
            &self,
            request: tonic::Request<super::UnlockRequest>,
        ) -> std::result::Result<tonic::Response<super::UnlockResponse>, tonic::Status>;
        /// Locks resources for another user
        async fn admin_lock(
            &self,
            request: tonic::Request<super::AdminLockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AdminLockResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct LockServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> LockServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for LockServiceServer<T>
    where
        T: LockService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/urc.lock.LockService/Lock" => {
                    #[allow(non_camel_case_types)]
                    struct LockSvc<T: LockService>(pub Arc<T>);
                    impl<T: LockService> tonic::server::UnaryService<super::LockRequest>
                    for LockSvc<T> {
                        type Response = super::LockResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LockService>::lock(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LockSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/urc.lock.LockService/Query" => {
                    #[allow(non_camel_case_types)]
                    struct QuerySvc<T: LockService>(pub Arc<T>);
                    impl<T: LockService> tonic::server::UnaryService<super::QueryRequest>
                    for QuerySvc<T> {
                        type Response = super::QueryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LockService>::query(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QuerySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/urc.lock.LockService/Status" => {
                    #[allow(non_camel_case_types)]
                    struct StatusSvc<T: LockService>(pub Arc<T>);
                    impl<
                        T: LockService,
                    > tonic::server::UnaryService<super::StatusRequest>
                    for StatusSvc<T> {
                        type Response = super::StatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LockService>::status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/urc.lock.LockService/Unlock" => {
                    #[allow(non_camel_case_types)]
                    struct UnlockSvc<T: LockService>(pub Arc<T>);
                    impl<
                        T: LockService,
                    > tonic::server::UnaryService<super::UnlockRequest>
                    for UnlockSvc<T> {
                        type Response = super::UnlockResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnlockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LockService>::unlock(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnlockSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/urc.lock.LockService/AdminLock" => {
                    #[allow(non_camel_case_types)]
                    struct AdminLockSvc<T: LockService>(pub Arc<T>);
                    impl<
                        T: LockService,
                    > tonic::server::UnaryService<super::AdminLockRequest>
                    for AdminLockSvc<T> {
                        type Response = super::AdminLockResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AdminLockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LockService>::admin_lock(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AdminLockSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for LockServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "urc.lock.LockService";
    impl<T> tonic::server::NamedService for LockServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
