# =============================================================================
# Lore Server GitHub Actions Configuration
# =============================================================================
# This configuration is used for CI testing in GitHub Actions.

[server.grpc]
port = 41338

[server.quic]
port = 41338

[server.quic.certificate]
cert_file = "cert.pem"
pkey_file = "key.pem"

[server.quic_internal]
enabled = true
# the certs being generated locally aren't compatible with WebPkiClientVerifier
# because it is strict about the CA constraint
verify_client_certs = false

[server.quic_internal.certificate]
cert_file = "cert.pem"
pkey_file = "key.pem"

[server.http]
presigned_url_hmac_key = "32d0bd7711276da5a4d73e1211ba3884ad1819aa0b4727b8ee5d695e9c3199de"

# =============================================================================
# Store Configuration
# =============================================================================

[immutable_store]
mode = "local"

[mutable_store]
mode = "local"

[lock_store]
mode = "local"

# =============================================================================
# Local Store Configuration (Predefined Type)
# =============================================================================

[immutable_store.local]
path = "./"
flush_delay_seconds = 10

[mutable_store.local]
path = "./"
flush_delay_seconds = 10

# =============================================================================
# Telemetry Configuration
# =============================================================================

[telemetry.logger]
format = "text"

# =============================================================================
# Notification Configuration
# =============================================================================

[notification]
mode = "local"

# =============================================================================
# Other Features Configuration
# =============================================================================

[feature]
history_step_size = 10
