// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// SPDX-License-Identifier: MIT
//! FFI error code trait.
//!
//! [`FfiError`] provides a standard way for error types to expose an integer
//! error code suitable for FFI boundaries. Discrete error types implement this
//! trait directly, and error sets auto-inherit FFI codes via generated
//! delegation.

/// Trait for errors that carry an FFI-compatible integer error code.
///
/// Discrete error types implement this trait to define their FFI code once.
/// Error sets generated by `#[error_set]` automatically delegate to each
/// variant's `ffi_code()`.
///
/// # Example
///
/// ```
/// use lore_error_set::FfiError;
///
/// #[derive(Debug)]
/// struct NotFound;
///
/// impl std::fmt::Display for NotFound {
///     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
///         write!(f, "not found")
///     }
/// }
///
/// impl std::error::Error for NotFound {}
///
/// impl FfiError for NotFound {
///     fn ffi_code(&self) -> i32 { 1 }
/// }
///
/// let err = NotFound;
/// assert_eq!(err.ffi_code(), 1);
/// ```
pub trait FfiError {
    /// Returns the FFI error code for this error.
    fn ffi_code(&self) -> i32;
}
